# .github/workflows/rust.yml
name: Rust

on: [pull_request, push]

jobs:
  quality:
    runs-on: [self-hosted, nixos]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: fmt
        run: nix develop --command cargo fmt --check

      - name: clippy
        run: nix develop --command cargo clippy -- -D warnings

      - name: test
        run: nix develop --command cargo test

      - name: cargo-deny (licenças + advisories)
        run: nix develop --command cargo deny check

      - name: cargo-audit
        run: nix develop --command cargo audit
